export const defaulTvShowSchema = {
  name: 1,
  originalName: 1,
  lastRating: 1,
  overview: 1,
  lastPopularity: 1,
  firstAirDate: 1,
  lastAirDate: 1,
  posterImage: 1,
  backdropImage: 1,
  adult: 1,
  createBy: 1,
  genres: 1,
  homepage: 1,
  inProduction: 1,
  lastEpisodeToAir: 1,
  nextEpisodeToAir: 1,
  numberOfEpisodes: 1,
  numberOfSeasons: 1,
  tagline: 1,
  productionCompanies: 1,
  status: 1,
  updatedAt: 1,
};
